### ISSUE TITLE
Invalid Content-Length

### ISSUE THREAD

**Issue by suzuryo** [stephenlb/nodejuice#3]
I use "multi byte character (encoding: utf-8)", such as Japanese Language.  

"body.length" returns the number of characters in a string.  
so I think that is invalid content-length because string is multi byte character.  

"Buffer.byteLength" returns the actual byte length of a string.  

```
--- servers/wsgi.js.orig    2010-06-26 11:42:16.000000000 +0900
+++ servers/wsgi.js 2010-11-10 13:30:38.000000000 +0900
@@ -55 +55 @@
-        headers["Content-Length"] = body.length;
+        headers["Content-Length"] = Buffer.byteLength(body);
```

**Comment by stephenlb** [comment]
thank you for the patch.  applied and published.

**Comment by suzuryo** [comment]
Any other Content-Length caluculating code may need patches.

**Comment by stephenlb** [comment]
Yup. The Seeker Server needed this patch as well.  Thank you again Suzuryo.
